# Generated by Django 5.1.4 on 2025-01-22 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_equipe_alter_projeto_orcamento_projeto_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(help_text='(99) 99999-9999', max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')])),
                ('ativo', models.BooleanField(default=True)),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='nucleo.equipe')),
            ],
        ),
    ]
