# Generated by Django 5.1.4 on 2025-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
