# Generated by Django 5.1.4 on 2025-02-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_alter_tarefa_data_fim_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
        ),
    ]
